// <auto-generated />
using Algorithm.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Algorithm.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230517211522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Algorithm.Model.Algorithm", b =>
                {
                    b.Property<int>("ID_ALGORITHM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ALGORITHM"));

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE_SOURCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LEVEL")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATH_TO_PRESENTATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_ALGORITHM");

                    b.ToTable("ALGORITHMS");
                });

            modelBuilder.Entity("Algorithm.Model.Courses", b =>
                {
                    b.Property<int>("ID_COURSE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_COURSE"));

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE_SOURCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PRICE")
                        .HasColumnType("float");

                    b.HasKey("ID_COURSE");

                    b.ToTable("COURSES");
                });

            modelBuilder.Entity("Algorithm.Model.Question", b =>
                {
                    b.Property<int>("ID_QUESTION")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_QUESTION"));

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.Property<string>("QUESTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_QUESTION");

                    b.ToTable("QUESTIONS");
                });

            modelBuilder.Entity("Algorithm.Model.Test", b =>
                {
                    b.Property<int>("ID_TEST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TEST"));

                    b.Property<string>("IMAGE_SOURCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LEVEL")
                        .HasColumnType("int");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOURCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TEST");

                    b.ToTable("TESTS");
                });

            modelBuilder.Entity("Algorithm.Model.User", b =>
                {
                    b.Property<int>("ID_USER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USER"));

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE_SOURCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LEVEL")
                        .HasColumnType("int");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_USER");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Algorithm.Model.User_Activity", b =>
                {
                    b.Property<int>("ID_USER_ACTIVITY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USER_ACTIVITY"));

                    b.Property<int>("ID_ALGORITHM")
                        .HasColumnType("int");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.HasKey("ID_USER_ACTIVITY");

                    b.ToTable("USER_ACTIVITY");
                });

            modelBuilder.Entity("Algorithm.Model.User_Courses", b =>
                {
                    b.Property<int>("ID_USER_COURSE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USER_COURSE"));

                    b.Property<int>("ID_COURSE")
                        .HasColumnType("int");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.HasKey("ID_USER_COURSE");

                    b.ToTable("USER_COURSES");
                });

            modelBuilder.Entity("Algorithm.Model.User_Test", b =>
                {
                    b.Property<int>("ID_USER_TEST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USER_TEST"));

                    b.Property<int>("ID_TEST")
                        .HasColumnType("int");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.HasKey("ID_USER_TEST");

                    b.ToTable("USER_TESTS");
                });
#pragma warning restore 612, 618
        }
    }
}
